FROM node:18 as build

WORKDIR /app

COPY . .

RUN npm ci --legacy-peer-deps

RUN npm install -g nx

RUN nx build shell

RUN nx reset && nx server shell

RUN cp dist/apps/shell/server/server.js .

CMD node server.js --host 0.0.0.0



